export {default as Navbar } from './Navbar'
export {default as Home } from './Home'
export {default as About} from './About'
export {default as Doctors} from './Doctors'
export {default as Core} from './Core'
export {default as End} from './End'
export {default as Login} from './Login'
